#!/usr/bin/env bash
# This script is displaying "Best School" 8 times, "bad luck" once and "good luck" once.
n=0
while [ "$n" -lt 10 ]
do
    if [ "$n" -eq 3 ]
    then
	echo "bad luck"
    elif [ "$n" -eq 7 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((n++))
done
