#!/usr/bin/env bash
# This script displays numbers from 1-20 and replaces 4,9, and 17 with strings.
n=1
while [ "$n" -le 20 ]
do
    case "$n" in
	4)
	    echo "$n"
	    echo "bad luck from China"
	    ;;
	9)
	    echo "$n"
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "$n"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$n"
	    ;;
    esac
    ((n++))
done
