#!/usr/bin/env bash
# manages ./manage_my_process.
#!/bin/bash

PID_FILE="/var/run/my_process.pid"
MANAGE_SCRIPT="./manage_my_process"

# Creates a job in bg and PID is retireved from $! variable.
start_process() {
    sudo $MANAGE_SCRIPT &
    sudo sh -c "echo '$!' > $PID_FILE"
    echo "manage_my_process started"
}

stop_process() {
    sudo kill "$(cat "$PID_FILE")"
    sudo rm -f "$PID_FILE"
    echo "manage_my_process stopped"
}

restart_process() {
    sudo kill "$(cat "$PID_FILE")"
    sudo rm -f "$PID_FILE"
    sudo $MANAGE_SCRIPT &
    sudo sh -c "echo '$!' > $PID_FILE"
    echo "manage_my_process restarted"
}

case $1 in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
