#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
#+ Displays I am invincible!!! when receiving a SIGTERM signal.
trap "echo \"I am invincible!!!\"" SIGTERM
n=0
while [ "$n" -lt 1 ]
do
    echo "To infinity and beyond"
    sleep 2
done
